[tool.poetry]
name = "pubmed_project"
version = "0.1.0"
description = "Fetch research papers from PubMed and process their metadata."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28"
argparse = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
